const sb=supabase.createClient(window.SUPABASE_URL,window.SUPABASE_PUBLISHABLE_KEY);let user;const $=x=>document.getElementById(x),day=()=>new Date().toISOString().slice(0,10);
async function boot(){const {data}=await sb.auth.getSession();if(data.session){user=data.session.user;openApp();loadToday()}else openLogin()}function openApp(){$('login').hidden=true;$('app').hidden=false}function openLogin(){$('login').hidden=false;$('app').hidden=true}
sb.auth.onAuthStateChange((_,s)=>{user=s?.user;if(user)openApp();else openLogin()});
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginError').textContent='';const {error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error)$('loginError').textContent=error.message};$('logout').onclick=()=>sb.auth.signOut();
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');const p=b.dataset.page;$('today').hidden=p!=='today';$('progress').hidden=p!=='progress';$('title').textContent=p==='today'?"Today's Check-in":"Progress";if(p==='progress')loadProgress()});
async function loadToday(){const {data}=await sb.from('daily_checkins').select('*').eq('user_id',user.id).eq('date',day()).maybeSingle();if(!data)return;['weight','calories','protein','carbs','fat','mood','energy','hunger','food','reflection'].forEach(k=>{if(data[k]!=null)$(k).value=data[k]})}
$('checkin').onsubmit=async e=>{e.preventDefault();$('saveMsg').textContent='Saving…';const row={user_id:user.id,date:day()};['weight','calories','protein','carbs','fat','energy','hunger'].forEach(k=>{const v=$(k).value;row[k]=v===''?null:Number(v)});['mood','food','reflection'].forEach(k=>row[k]=$(k).value||null);const {error}=await sb.from('daily_checkins').upsert(row).select().single();if(error){$('saveMsg').textContent=error.message;return}const f=$('photo').files[0];if(f){const ext=(f.name.split('.').pop()||'jpg').toLowerCase();const path=`${user.id}/${day()}-${crypto.randomUUID()}.${ext}`;const r=await sb.storage.from('progress-photos').upload(path,f);$('photoMsg').textContent=r.error?'Photo upload failed: '+r.error.message:'Photo uploaded privately.';$('photo').value=''}$('saveMsg').textContent='Saved ✓'};
async function loadProgress(){const {data,error}=await sb.from('daily_checkins').select('*').eq('user_id',user.id).order('date');if(error){$('history').textContent=error.message;return}const w=data.filter(x=>x.weight!=null),first=w[0]?.weight,last=w.at(-1)?.weight;$('stats').innerHTML=`<div><strong>${last??'—'} kg</strong><small>Latest</small></div><div><strong>${first!=null&&last!=null?(last-first).toFixed(1):'—'} kg</strong><small>Change</small></div><div><strong>${data.length}</strong><small>Check-ins</small></div>`;draw(w);$('history').innerHTML=data.slice().reverse().slice(0,12).map(x=>`<div><b>${x.date}</b> · ${x.weight??'—'} kg · ${x.mood??''}</div>`).join('')||'<p>No check-ins yet.</p>';loadPhotos()}
function draw(rows){const c=$('chart'),ctx=c.getContext('2d'),w=c.clientWidth||800,h=280,dpr=devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);if(!rows.length){ctx.fillText('Add a weight to start your graph.',20,30);return}const vals=rows.map(x=>+x.weight),min=Math.min(...vals)-1,max=Math.max(...vals)+1;ctx.beginPath();rows.forEach((x,i)=>{const px=25+(w-45)*i/Math.max(1,rows.length-1),py=20+(h-45)*(1-(x.weight-min)/(max-min||1));i?ctx.lineTo(px,py):ctx.moveTo(px,py)});ctx.stroke();}
async function loadPhotos(){const {data}=await sb.storage.from('progress-photos').list(user.id,{limit:50,sortBy:{column:'name',order:'desc'}});if(!data?.length){$('photos').innerHTML='<p>No photos yet.</p>';return}const imgs=await Promise.all(data.map(async f=>{const r=await sb.storage.from('progress-photos').createSignedUrl(`${user.id}/${f.name}`,3600);return r.data?.signedUrl?`<img src="${r.data.signedUrl}" alt="Progress photo">`:''}));$('photos').innerHTML=imgs.join('')||'<p>No photos yet.</p>'}boot();
